version: '2.4'

networks:
  proxy-redirect:
    external: true
    name: proxy-redirect
    driver: bridge

services:
  example-client:
    build: ./
    image: 'example-client:1.0.0'
    restart: always
    networks:
      - proxy-redirect
    volumes:
      - './auth/appsecrets.json:/src/app/appsecrets.json'
    mem_limit: 128mb
    ports:
      - 5200:5200